version: '3.8'

services:
  api:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - JWT_SECRET=${JWT_SECRET}
      - WHISPER_PATH=${WHISPER_PATH}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"